module.exports = { agent:
   { x: 0,
     y: 0,
     r: 0,
     da: 0,
     dt: 0,
     alive: true,
     hasGold: false,
     win: false,
     inRoomIds: [ 63 ] },
  rooms: 
   [ { x: 0,
       y: 0,
       id: 63,
       hasPit: false,
       hasGold: false,
       hasExit: true,
       visible: true,
       '$$hashKey': 'object:6',
       senses: [Object] },
     { x: 0,
       y: 86.4,
       id: 67,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:7',
       senses: [Object] },
     { x: 86.4,
       y: 0,
       id: 65,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:8',
       senses: [Object] },
     { x: 0,
       y: -86.4,
       id: 66,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:9',
       senses: [Object] },
     { x: 172.8,
       y: 0,
       id: 73,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:10',
       senses: [Object] },
     { x: -86.4,
       y: 86.4,
       id: 68,
       hasPit: false,
       hasGold: true,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:11',
       senses: [Object] },
     { x: 86.4,
       y: 86.4,
       id: 69,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:12',
       senses: [Object] },
     { x: -86.4,
       y: 172.8,
       id: 87,
       hasPit: true,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:13',
       senses: [Object] },
     { x: -86.4,
       y: -86.4,
       id: 76,
       hasPit: true,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:14',
       senses: [Object] },
     { x: 0,
       y: -172.8,
       id: 78,
       hasPit: false,
       hasGold: false,
       hasExit: false,
       visible: true,
       '$$hashKey': 'object:15',
       senses: [Object] } ],
  bounds: { minx: -134.4, maxx: 220.8, miny: -220.8, maxy: 220.8 } }
;